### ISSUE TITLE
Subtitles not showing up

### ISSUE THREAD

**Issue by php-wizard** [ThemeZee/palm-beach#1]
Hello,
i want to show subtitles under a post title both in a post page and post excerpt.

I have tried different plugins, like WP Subtitles and KIA Subtitles , but subtitles are not showing up.

How can i achieve that with this theme?
Thank you in advance

**Comment by Netzberufler** [comment]
Hi there,

These plugins work by adding their template tags to the theme files. You should create a child theme in order to do that. You can also find some instructions on the plugin pages.

It is not an issue with the theme.

Best,
Thomas
